language: objective-c
osx_image: xcode8.3
xcode_workspace: Gallery.xcworkspace
xcode_scheme: GalleryTests

branches:
  only:
    - develop
    - master
env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
before_install:
  - rvm install ruby-2.2.2
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
